export interface ChangelogEntry {
  version: string;
  date: string;
  changes: string[];
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '2.4.0',
    date: '2026-08-06 · 00h35',
    changes: [
      'Nouvelle direction artistique : crème + vert forêt profond (clair), vert forêt + or (sombre)',
      'Tous les tokens couleur/arrondi/ombre revus pour un rendu premium cohérent',
      'Boutons pill, cartes arrondies (20-28px), palette chaude sur toute l\'app',
      'Fix contraste : icônes invisibles en mode sombre (Paramètres, Messages)',
      'Bouton actif nav/onglets : vert en clair, or en sombre',
      'Installation du skill design ui-ux-pro-max (84 styles, 192 palettes, guidelines UX)',
    ],
  },
  {
    version: '2.3.0',
    date: '2026-08-03 · 14h10',
    changes: [
      'Backend redéployé (Mac local + tunnel) après expiration Railway',
      'Like / Favori / Vue : unique par compte, plus de double-comptage',
      'Feed Pour toi : exclut désormais ses propres vidéos',
      'Pour toi : nom affiché au lieu du nom d\'utilisateur',
      'Icônes son et badge x1 retirés des vidéos',
      'Boutons profil/like/commentaire/partage recentrés au milieu droit',
      'Long-press sur une vidéo → menu republier / partager / ajouter à une collection',
      'Favoris : onglets Vidéos, Sons, Collections',
      'Collections : création + ajout de vidéos depuis une vidéo',
      'Swipe vertical dans ses propres vidéos depuis le profil',
      'Publier : sélection multiple de photos depuis la galerie',
      'Fils : ajout de plusieurs photos, affichage en galerie horizontale',
      'Fix : bug de saisie dans la description à la publication',
      'Story : bouton "+" depuis la messagerie',
      'Modifier le profil : photo de couverture personnalisable',
      'Live/vidéo dans Pour toi : recadrage, plus de débordement sur la vidéo suivante',
      'Notifications : pseudo affiché dans chaque notification',
      'Labels : "Pourtoi" et "Like" à la place de "feed" et "j\'aime"',
      'Admin : pages Comments et Settings, gestion des rôles admin',
    ],
  },
  {
    version: '2.2.0',
    date: '2026-06-05 · 22h00',
    changes: [
      'Swipe gauche sur vidéo → panel profil depuis la droite',
      'Splash screen animé au lancement (logo, tagline, dots)',
      'Écran erreur personnalisé (remplace l\'écran rouge)',
      'Double-tap coeur : animation bounce + float (style TikTok)',
      'Pull-to-refresh sur tous les feeds vidéo',
      'Boutons actions : spring bounce au tap',
      'Préchargement vidéos optimisé (démarrage 2× plus rapide)',
      'Tabs header : Pour toi actif bold, underline 2.5px',
      'Skeleton loading : profil utilisateur, grille posts, commentaires',
      'Dark mode : Explore, Messages, PostDetail, Onboarding',
      'Onboarding redesigné : icônes, dots animés, bouton pill',
      'Notifications : filtre par onglet + mark-all read',
      'Live : compteur viewers temps réel (Socket.IO)',
      'Follow dot rouge (style TikTok)',
    ],
  },
  {
    version: '2.1.0',
    date: '2026-06-05 · 15h00',
    changes: [
      'Live : erreur 500 corrigée (migrations DB appliquées)',
      'Partage : pop-up TikTok avec contacts, republier, apps externes',
      'Republier : affiche le badge repost + avatar en bas à gauche',
      'Pas intéressé(e) : retire le contenu du feed Pour toi',
      'Ajouter à la Story : post visible 24h sur le profil',
      'Signaler : formulaire envoyé directement au support admin',
      'Isolation cache inter-comptes : données du compte précédent effacées',
      'Video horizontale : bouton Plein écran + resizeMode auto',
      'Commentaires : header N commentaires + icône filtre',
      'Haptic feedback sur like, double-tap, partage',
      'Version bump : 2.1.0 (build 4)',
    ],
  },
  {
    version: '2.0.0',
    date: '2026-06-05 · 13h00',
    changes: [
      'Feed: 1 video plein ecran par page (pagingEnabled fix)',
      'Explorer: grille trending fonctionnelle + theme uniforme',
      'Profil: grille videos visible (filtres restrictifs retires)',
      'Profil: stats dark mode lisibles, bouton Modifier visible',
      'Sheet Creer: IcLive icon remplace emoji interdit',
      'Seek bar: 4px + primaryLight + thumb 16px visible',
      'Caption / actions remontees au-dessus seek bar',
      'Messages: empty state centre verticalement',
      'Upload: thumbnail_url Cloudinary auto a chaque upload',
      'Backend: cover_url + following list + creator stats',
    ],
  },
  {
    version: '1.9.0',
    date: '2026-06-04 · 11h00',
    changes: [
      'Seek bar: drag fluide (pageX, terminationRequest false)',
      'Seek bar: remontee de 12px, zone tactile 44px',
      'Nav bar: gap reduit en bas de l\'ecran',
      'Commentaire: clavier s\'ouvre auto a la reponse',
      'Preview video profil: createThumbnail lazy + cache memoire',
      'Vinyl disc tournant sur chaque video avec son',
      'Sound sheet: utiliser / voir toutes les videos / telecharger',
    ],
  },
  {
    version: '1.8.0',
    date: '2026-06-04 · 09h30',
    changes: [
      'Notifications : 4 onglets (Tous / J\'aime / Commentaires / Abonnés)',
      'Notifications : badges par onglet + navigation vers le contenu',
      'Notifications : live -> ouvre directement le stream',
      'Profil : bouton Partager (lien universel nour.app)',
      'Bio : liens cliquables (http/https ouvrent le navigateur)',
      'Video : single-tap pause plus rapide (200ms au lieu de 300ms)',
      'Video : replay automatique en boucle (seek 0 a la fin)',
      'Commentaires : "Voir plus" pour charger + de commentaires',
    ],
  },
  {
    version: '1.7.0',
    date: '2026-06-04 · 08h00',
    changes: [
      'DA: design TikTok pur — video plein ecran sans chevauchement nav bar',
      'DA: avatar vert (ring vert), hashtags en vert, badge verifie vert',
      'DA: bouton + navigation cercle (style image reference)',
      'Seek bar draggable: glisser pour avancer/reculer dans la video',
      'Upload video: remplacement XHR par fetch (plus fiable iOS)',
      'Messagerie H->H et F->F corrigee (genre bien inclus dans le profil)',
      'Reponses commentaires: "Voir N reponses" inline',
      'Barre de progression visible au-dessus de la nav (hauteur ITEM_H)',
    ],
  },
  {
    version: '1.6.0',
    date: '2026-06-04 · 06h00',
    changes: [
      'Onglet "Suivis" dans le feed — videos des comptes suivis',
      'Live streaming corrige — viewer recoit la camera du broadcaster',
      'Barre de progression verte sur chaque video',
      'Badge duree video (haut gauche)',
      'Commentaires : liker, repondre, supprimer les siens',
      'Badge rouge sur onglet Boite (notifications non-lues)',
      'J\'aime : sous-onglets "Pour toi" et "Fils"',
      'Navigation : "Boite" (ex-Messages), bouton Live en haut gauche',
      'Dark theme pur noir (#0A0A0A) style TikTok',
      'Theme clair premium (gris perle)',
      'Icone recherche en haut droite du feed',
      'Photo de couverture sur les videos dans le profil (Cloudinary)',
      'Avatars personnalises : sauvegarde + propagation corrigees',
      'Messagerie H->H et F->F : fonctionne meme si conversation existante',
    ],
  },
  {
    version: '1.5.0',
    date: '2026-06-04 · 02h06',
    changes: [
      'Messagerie H→H et F→F : directe, sans restriction ni demande',
      'Messagerie H↔F : restreinte (règle islamique)',
      'Onboarding 3 écrans au premier lancement',
      'Fils — clic sur un fil → ouvre le détail avec réponses',
      'Fils — répondre à un fil depuis ThreadDetailScreen',
      'Signalement utilisateur + contenu fonctionnel',
      'Blocage utilisateur (block/unblock toggle)',
      'Masquer un utilisateur du feed',
      'Backend : routes /messages/direct, /block, /hide, /reports',
    ],
  },
  {
    version: '1.4.0',
    date: '2026-06-04 · 02h00',
    changes: [
      'Thumbnail automatique : première image de la vidéo extraite à l\'upload',
      'Création de fils corrigée (POST /threads erreur 404 résolue)',
      'Swipe droite→gauche sur vidéo → profil utilisateur avec animation',
      'Profil utilisateur : bouton options (signaler, bloquer, masquer du feed)',
      'Avatar sauvegardé correctement sur le serveur (bug schema corrigé)',
      'Avatar propagé partout : feed, fils, messages, profil',
      'Commentaires : bottom sheet draggable ½ écran, vidéo continue derrière',
      'VideoPlayerScreen : ouvrir une vidéo en plein écran depuis le profil',
      'Notifications : bell avec badge dans Messages, historique cliquable',
      'Stats profil : recalculées en temps réel depuis la DB',
      'Vidéos se mettent en pause quand on quitte l\'onglet',
    ],
  },
  {
    version: '1.3.0',
    date: '2026-06-04 · 01h18',
    changes: [
      'Thème Clair / Sombre / Système appliqué à toute l\'app',
      'Double-tap sur vidéo → like animé (cœur rose)',
      'Tap sur "Pour Toi" → rafraîchissement du feed',
      'Son de la vidéo cliquable avec page dédiée',
      'Partage natif (WhatsApp, iMessage, copier lien)',
      'Barre de navigation redesignée',
      'Upload : hashtags et mentions @utilisateur',
      'Progress bar réelle pendant l\'upload',
      'Paramètres entièrement fonctionnels avec persistance',
      'Changement de mot de passe depuis les paramètres',
      'Photo de profil modifiable',
      'Onglets Profil : Vidéos, Fils, J\'aime, Favoris',
      'Algorithm amélioré avec watch time',
    ],
  },
  {
    version: '1.2.0',
    date: '2026-06-03 · 23h49',
    changes: [
      'Feed TikTok fullscreen scroll vertical',
      'Bouton + → choix Vidéo / Fil',
      'ThreadComposer avec image et vidéo',
      'Système de favoris (save) fonctionnel',
      'Explorer avec grille 3 colonnes et recherche',
      'Dark mode (hook useTheme)',
      'Route /posts/liked backend',
      'Migration PostView pour watch time',
    ],
  },
  {
    version: '1.1.0',
    date: '2026-06-02 · 21h30',
    changes: [
      'Navigation : Accueil, Explorer, +, Messages, Profil',
      'Overlay vidéo : like, commentaire, partage, favoris',
      'Système de fils (threads) style Twitter',
      'Modifier le profil (nom, bio)',
      'Routes backend : threads, favorites, follow',
      'Algorithme feed TikTok (score engagement + decay)',
      'Tracking des vues vidéo',
    ],
  },
  {
    version: '1.0.0',
    date: '2026-06-01 · 18h00',
    changes: [
      'Lancement de l\'app Nour',
      'Inscription et connexion',
      'Upload vidéo et image',
      'Feed vertical fullscreen',
      'Profil utilisateur',
      'Messages et conversations',
      'Système de notifications',
    ],
  },
];
